version: "3.8"

networks:
  node-network:
    driver: bridge

services:

    nodeserver:
        build:
            context: ./app
        ports:
            - "3000:3000"
        networks:
          - node-network
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        depends_on:
          - db
        tty: true

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
          - "80:80"
        depends_on:
          - nodeserver
        networks:
          - node-network

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true # Necessário habilitar para usar o modo interativo
        volumes:
          - ./mysql:/var/lib/mysql
        environment:
          - MYSQL_DATABASE=nodedb
          - MYSQL_ROOT_PASSWORD=root
        networks:
          - node-network